services:
  gtfs2map:
    build: .
    environment:
      - GTFS_STATIC_URL
      - GTFS_REALTIME_METHOD
      - GTFS_REALTIME_HTTP_TRIP_UPDATES_URL
      - GTFS_REALTIME_HTTP_VEHICLE_POSITIONS_URL
      - GTFS_REALTIME_HTTP_SERVICE_ALERTS_URL
      - GTFS_REALTIME_MQTT_BROKER_HOST
      - GTFS_REALTIME_MQTT_BROKER_PORT
      - GTFS_REALTIME_MQTT_BROKER_USERNAME
      - GTFS_REALTIME_MQTT_BROKER_PASSWORD
      - GTFS_REALTIME_MQTT_TRIP_UPDATES_TOPIC
      - GTFS_REALTIME_MQTT_VEHICLE_POSITIONS_TOPIC
      - GTFS_REALTIME_MQTT_SERVICE_ALERTS_TOPIC
      - APP_TEMPLATE_ID
      - APP_TEMPLATE_TITLE
      - APP_TEMPLATE_COLOR
      - APP_DATETIME_FORMAT
      - APP_DATE_FORMAT
      - APP_TIME_FORMAT
      - APP_UNMATCHED_VEHICLES_ENABLED
      - APP_TEMPLATE_CREDITS
    volumes:
      - ./view/${APP_TEMPLATE_ID}:/data/j2/input:ro
      - ./output/${APP_TEMPLATE_ID}:/data/html/output:rw