services:
  gtfsrtmapfx:
    build: .
    environment:
      - GTFS_STATIC_URL
      - GTFS_REALTIME_TRIP_UPDATES_URL
      - GTFS_REALTIME_VEHICLE_POSITIONS_URL
      - GTFS_REALTIME_SERVICE_ALERTS_URL
      - APP_TEMPLATE_ID
      - APP_TEMPLATE_TITLE
      - APP_TEMPLATE_COLOR
      - APP_TEMPLATE_CREDITS
    volumes:
      - ./view/${APP_TEMPLATE_ID}:/data/j2/input:ro
      - ./output/${APP_TEMPLATE_ID}:/data/html/output:rw
    ports:
      - "8080:8080"